language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - mv phpunit.xml.dist phpunit.xml

install:
  - travis_retry composer update --prefer-source $PREFER_LOWEST

script:
  - phpunit

branches:
  only:
    - master
    - dev